apps/products/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

import views


urlpatterns = [
    url(r'^metrics/create/$', views.MetricFormView.as_view(), name='metrics-create'),
    url(r'^metrics/update/(?P<pk>.*\d+)/$', views.UpdateMetrics.as_view(), name='update-metrics'),
    url(r'^metrics/delete/(?P<pk>.*\d+)/$', views.DeleteMetrics.as_view(), name='delete-metrics'),
    url(r'^(?P<pk>.*\d+)/metrics/$', views.ProductMetricsView.as_view(), name='product-metrics'),
    url(r'^metrics/$', views.MetricsView.as_view(), name='metrics'),

    url(r'^similar/(?P<pk>.*\d+)/$', views.ProductSimilarView.as_view(), name='product-similar'),
    url(r'^similar-images/(?P<pk>.*\d+)/$', views.ProductSimilarImagesView.as_view(), name='product-similar-images'),
    url(r'^selling/$', views.ProductSellingSpeedView.as_view(), name='selling_speed'),

    url(r'^create/$', views.CreateProduct.as_view(), name='create'),
    url(r'^download/$', views.download_file, name='download'),
    url(r'^download_status/$', views.download_status, name='download_status'),

    url(r'update/(?P<pk>.*\d+)/$',
        views.ProductUpdateView.as_view(),
        name='update'),

    url(r'delete/(?P<pk>.*\d+)/$',
        views.ProductDeleteView.as_view(),
        name='delete'),

    url(r'^VisitProduct/(?P<myAffiliateId>.+)/$', views.VisitProduct),

    url(r'^visitor-status/(?P<pk>.*\d+)/$', login_required(views.ListVisitorStatus.as_view()), name='visitor-status'),
    url(r'^VisitorStatus/Delete/(?P<pk>[0-9]+)/next=(?P<next>.+)/$',
        views.DeleteVisitorStatusView.as_view(),
        name='DeleteVisitorStatus'),

    url(r'^$', views.ProductListView.as_view(), name='list'),
]

goodobtain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from products.views import AdminCrawlSpiderView, AdminScrapyFormView
from . views import IndexView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view()),

    url(r'^admin/scrapy-crawl/(?P<spider>.*\w+)/$', AdminCrawlSpiderView.as_view(), name='crawl-spider'),
    url(r'^admin/scrapy/$', AdminScrapyFormView.as_view(), name='scrapy'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^crawler/', include('crawler.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^captcha/', include('captcha.urls')),
)

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += patterns('',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )
    except ImportError:
        pass

apps/products/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings
from django.core.mail import send_mail

from .models import (
    Category,
    Website,
)

#import ipdb


class ScrapyFormView(forms.Form):
    """
    Form that accepts scrapy commands
    """
    SPIDERS = [
        ("lazadaAllShopSpider", "Lazada All Shop"),
        ("allShopSpider", "Bukalapak All Shop"),
        ("CategoryBukalapakSpider", "Bukalapak Categories"),
        ("ExistingBukalapakSpider", "Existing Bukalapak Products from Database"),
        ("tokoSpider", "Tokopedia active Categories"),
        ("existingTokoSpider", "Existing Tokopedia Category Products from Database")
    ]
    spider = forms.ChoiceField(choices=SPIDERS)


class FeedbackForm(forms.Form):
    """
    Form for sending feedback to admin@goodobtain.com
    """
    feedback = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.fields['feedback'].widget.attrs['class'] = 'form-control'

    def send_feedback(self):
        data = self.cleaned_data
        subject = "Crawler Site Feedback"
        message = data.get("feedback")
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [settings.ADMIN_EMAIL],
            fail_silently=False
        )


class ProductSearchForm(forms.Form):
    keywords = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(ProductSearchForm, self).__init__(*args, **kwargs)
        self.fields['keywords'].widget.attrs['class'] = 'form-control'


class ProductFilterForm(forms.Form):
    website = forms.ModelChoiceField(
        empty_label='All websites',
        queryset=Website.objects.all(),
        required=False,
    )
    category = forms.ModelChoiceField(
        empty_label='All categories',
        queryset=Category.objects.all(),
        required=False,
    )
    price = forms.IntegerField(
        label='Price higher than',
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(ProductFilterForm, self).__init__(*args, **kwargs)
        self.fields['category'].choices = self._get_category_choices()

    def _get_category_choices(self):
        choices = [(None, 'All categories')]
        for website in Website.objects.all().order_by('title'):
            choices.append(
                (
                    website.title,
                    [(category.id, '%s - %s' % (category.website, category.title)) for category in website.categories.all()]
                )
            )
        return choices

    def clean_category(self):
        website = self.cleaned_data.get('website')
        category = self.cleaned_data.get('category')
        if website and category:
            if category.website != website:
                raise forms.ValidationError("Category %s does not belong to %s" % (category, website))
        return category

apps/products/views.py
# -*- coding: utf-8 -*-
import os

from itertools import chain
from operator import and_
from datetime import datetime

from django.conf import settings
from django.shortcuts import render
from django.db.models import Q
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.utils.translation import ugettext as _
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView,
    FormView,
)

from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

from braces.views import (
    CsrfExemptMixin,
    JSONResponseMixin,
    AjaxResponseMixin,
    StaffuserRequiredMixin,
)

from . forms import (
    ScrapyFormView,
    FeedbackForm,
    ProductSearchForm,
    ProductFilterForm,
)

from .models import Product, VisitorStatus, Metrics, OwnProduct
from .tasks import download_file_task
from .utils import read_file

import logging
import coloredlogs
logger = logging.getLogger(__name__)
coloredlogs.install(level=logging.DEBUG)


class DownloadProduct(CreateView):
    model = Product
    fields = ['title']
    template_name = 'common/create.html'
    success_url = '/products/'


def download_file(request):
    # filename = "/tmp/tmpdata_" + random_str()
    # job = download_file_task.delay(filename)
    # return render(request, "products/download.html", {"job_id": job.id, "filename": filename})
    return HttpResponse(
        'This page was <b>disabled</b>. You can find more details '
        '<a href="https://trello.com/c/Lfx4jFSr/29-t0836-segment-fault">here</a>'
    )


def download_status(request):
    if 'job' in request.GET:
        job_id = request.GET['job']
    else:
        return HttpResponse('No job id given.')

    if 'file' in request.GET:
        filename = request.GET['file']
    else:
        return HttpResponse('No filename given.')

    status = download_file_task.AsyncResult(job_id)
    if status.ready():
        # ##################################
        # ##         ATTENTION!!!        ###
        # ## Probably performance issue  ###
        # ##################################
        response = HttpResponse(read_file(filename), content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename=download_data.csv'
        return response
    else:
        # return HttpResponseRedirect(reverse("products:download_status")+"?job="+job_id+"&file="+filename)
        return render(request, "products/download.html", {"job_id": job_id, "filename": filename})


def download_file2(request):
    import csv
    products = Product.objects
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=data.csv'

    writer = csv.writer(response)
    writer.writerow(
        ['URL', 'ID', 'internalId', 'Price', 'Stocks', 'Sales',
            'Page Views', 'Weight', 'Sales Rate', 'Similar Products', 'In stock'])

    for item in products.all()[0:10000]:
        writer.writerow([
            item.url,
            item.id,
            item.internalId,
            item.price,
            item.stock,
            item.sales,
            item.pageviews,
            item.weight,
            item.sales_rate,
            item.similar_products_num,
            item.in_stock
        ])

    return response


# TODO rename to ProductCreateView
class CreateProduct(StaffuserRequiredMixin, CreateView):
    model = Product
    fields = ['internalId', 'url', 'title', 'status']
    template_name = 'common/create.html'
    # BAD: hard-coded url. use 'reverse' instead
    success_url = '/products/'

    def form_valid(self, form):
        # Called when validation is passed
        # [](http://stackoverflow.com/questions/17826778/django-createview-is-not-saving-object)
        # [get field from form](http://stackoverflow.com/questions/4308527/django-model-form-object-has-no-attribute-cleaned-data)
        form.instance.url = form.cleaned_data['url']
        form.save()
        return super(CreateProduct, self).form_valid(form)


class MetricFormView(StaffuserRequiredMixin, CreateView):
    model = Metrics
    fields = ["product", "sales"]
    template_name = "common/create.html"
    success_url = '/products/metrics/'


class ProductListView(ListView):
    template_name = "products/list.html"
    model = Product
    filter_form_class = ProductFilterForm
    context_object_name = 'products'
    paginate_by = 25

    @method_decorator(csrf_exempt)
    def get(self, request, *args, **kwargs):
        self.filter_form = self.filter_form_class(request.GET)
        return super(ProductListView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(data=request.POST)
        if form.is_valid():
            form.send_feedback()
            messages.success(request, _("Thank you for sending us your feedback."))
            return HttpResponseRedirect(reverse("products:list"))
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        context["form"] = form
        return self.render_to_response(context)

    def get_sort_type(self):
        sort_type = self.request.GET.get("type", "asc")
        lookup = ["asc", "desc"]
        if sort_type not in lookup:
            sort_type = "asc"
        return sort_type

    def _get_sort_by_value(self):
        sort_type = self.get_sort_type()
        sort_by = self.request.GET.get("sort", "internalId")
        value = sort_by
        lookup = {
            "asc": {
                "stock": "stock",
                "internalId": "internalId",
                "weight": "weight",
                "price": "price",
                "pageviews": "pageviews",
                "sales": "sales",
                "sales_rate": "sales_rate",
                "similar_products": "similar_products_num",
                "similar_image_products": "similar_image_products_num",
            },
            "desc": {
                "stock": "-stock",
                "internalId": "-internalId",
                "weight": "-weight",
                "price": "-price",
                "pageviews": "-pageviews",
                "sales": "-sales",
                "sales_rate": "-sales_rate",
                "similar_products": "-similar_products_num",
                "similar_image_products": "-similar_image_products_num",
            }
        }
        if sort_type in lookup and sort_by in lookup[sort_type]:
            value = lookup[sort_type][sort_by]
        return value

    def get_website(self):
        try:
            return self.filter_form.cleaned_data.get('website')
        except:
            return

    def get_keywords(self):
        return self.request.GET.get("keywords", "").strip()

    def get_price(self):
        try:
            return self.filter_form.cleaned_data.get('price')
        except Exception:
            return

    def get_queryset(self):
        products = super(ProductListView, self).get_queryset()

        # default filter dict
        filter_dict = {'category__isnull': False}
        search_by_url = False  # "search by URL" flag
        search_by_keywords = False  # "search by keywords" flag

        if self.filter_form.is_valid():
            cd = self.filter_form.cleaned_data

            website = cd.get('website')
            if website:
                filter_dict.update({'category__website': website})

            category = cd.get('category')
            if category:
                filter_dict.update({'category': category})

            price = cd.get('price')
            if price:
                filter_dict.update({'price__gte': price})

        products = products.filter(**filter_dict)
        sort_by = self.request.GET.get("sort")
        keywords = self.get_keywords()

        if keywords:
            url_validate = URLValidator()
            try:
                # search by url
                url_validate(keywords)
                search_by_url = True
            except ValidationError:
                search_by_keywords = True

        if search_by_url:
            # search by url
            urls_parts = keywords.split('/')
            first_part = '/'.join(urls_parts[:-1])
            second_part = urls_parts[-1].split('-')

            query = '+'.join(["(CASE WHEN products_product.url LIKE '%%' || %s || '%%' THEN 1 ELSE 0 END)"] * len(second_part))
            # take products where rank >= 0.5
            products = products.filter(
                url__startswith=first_part
            ).extra(
                where=["({0})/{1}>=0.5".format(query, float(len(second_part))), ], params=second_part
            )

        elif search_by_keywords:
            # search by keywords
            products = products.filter(
                reduce(and_, (Q(title__icontains=kw) for kw in keywords.split()))
            )

        accepted_sorting = [
            "stock", "internalId", "weight", "price", "sales",
            "pageviews", "sales_rate", "similar_products",
            "similar_image_products"
        ]

        sort_value = self._get_sort_by_value()
        if sort_by in accepted_sorting:
            products = products.order_by(sort_value)
        # elif sort_by == "price":
        #     products = products.extra(select={
        #         "retail_price": "SELECT price FROM products_metrics \
        #         WHERE products_metrics.product_id = products_product.id \
        #         ORDER BY timestamp DESC LIMIT 1"
        #     })
        #     products = products.extra(order_by=[sort_value])

templates/products/detail.html
{% extends "common/base.html" %}
{% load i18n %}

{% block title %}{% trans "Products" %} {{product}}{% endblock title %}

{% block content %}
<h1>{% trans "Product" %} {{product}}</h1>

{% endblock content %}

templates/products/download.html
<meta http-equiv="Refresh" content="8;{% url 'products:download_status' %}?job={{ job_id }}&file={{ filename }}"/>
<title>Download</title>

Please wait for a moment to download. if download not start after the wait time. 
you can use this <a href="{% url 'products:download_status' %}?job={{ job_id }}&file={{ filename }}">direct link</a>

templates/products/list.html
{% extends "common/base.html" %}
{% load i18n %} 
{% load affiliate_extras %}
{% load product_tags %}
{% load bootstrap3 %}
{% load query_string %} 

{% block css %}
    {{ block.super }}
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
{% endblock %}

{% block title %}
    {% trans 'Products' %} 
{% endblock title %}

{% block content %}
    <div class="jumbotron">
        {% if search_form.errors %}
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {% for field in search_form %}
                    {% if field.errors %}
                    <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <form method="GET" action=".">
          {% if website %}<input type="hidden" name="website" value="{{ website.id }}">{% endif %}
          {% if category %}<input type="hidden" name="category" value="{{ category }}">{% endif %}
          {% if price %}<input type="hidden" name="price" value="{{ price }}">{% endif %}
            <div class="form-group">
                {{ search_form.keywords.label_tag }}
                {{ search_form.keywords }}
            </div>
            <input type="submit" class="btn btn-primary" value="Search" />
        </form>
    </div>

    {% if request.user.is_staff %}
        <div class="row">
            <a href="{% url 'products:create' %}" class="btn btn-primary ">
               <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                {% trans 'Create Product' %}
            </a>
            <a href="{% url 'products:download' %}" target="_blank" class="btn btn-primary">
               <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
               {% trans 'Download Data' %}
           </a>
        </div>
        <div class="clearfix">&nbsp;</div>
    {% endif %}

    <div class="row">
        <div class="col-md-9">
            <form action="." class="form-inline">
                {% bootstrap_field filter_form.website show_label=False %}
                {% bootstrap_field filter_form.category show_label=False %}
                {% bootstrap_field filter_form.price show_label=True %}
                <div class="form-group">
                    {% bootstrap_button "Filter" button_type="submit" button_class="btn-primary" icon='filter' %}
                </div>
            </form>
        </div>
    </div>

    {% if is_paginated %}
    <div class="row">
        <div class="col-md-12">
            <nav>
                <ul class="pager pull-right">
                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?{% make_query_string page=page_obj.previous_page_number %}">Previous</a>
                        </li>
                    {% else %}
                        <li class="disabled"><a href="#">Previous</a></li>
                    {% endif %}

                    <li>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</li>

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?{% make_query_string page=page_obj.next_page_number %}">Next</a>
                        </li>
                    {% else %}
                        <li class="disabled"><a href="#">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    {% endif %}
    </div>

    <div class="row x-overflow-auto">
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th>{% trans 'Metrics' %}</th>
                    <th>URL</th>
                    {% if request.user.is_staff %}
                        <th>ID</th>
                        <th><a href="{% url 'products:list' %}?sort=internalId&type={{ sort_type|switch_type }}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}{%if keywords %}&keywords={{ keywords }}{% endif %}">internalId</a></th>
                    {% endif %}
                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=price&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Price' %}</a></th>
                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=stock&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Stocks' %}</a></th>
                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=sales&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Sales' %}</a></th>
                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=pageviews&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Page Views' %}</a></th>
                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=weight&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Weight' %}</a></th>
                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=sales_rate&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Sales Rate' %}</a></th>
                    <th>
                        <a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=similar_products&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">
                        {% trans 'Similar Products' %}</a>
                    </th>

                    <th>
                        <a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=similar_products&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">
                        {% trans 'Manual Similar Products' %}</a>
                    </th>

                    <th>
                        <a href="" title="Manual Similar Products update time">
                        Updated
                        </a>
                    </th>

                    <th><a href="{% url 'products:list' %}?{% if page_obj.number > 1 %}page={{ page_obj.number }}&{% endif %}sort=similar_image_products&type={{ sort_type|switch_type }}{%if keywords %}&keywords={{ keywords }}{% endif %}{% if filter_ws %}&website_filter={{ filter_ws }}{% endif %}">{% trans 'Similar Images Products' %}</a></th>
                    <th>In stock</th>
                    {% if request.user.is_staff %}
                        <th>{% trans 'Update' %}</th>
                        <th>{% trans 'Delete' %}</th>
                        <th>Visitor status</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td>[<a href="{% url 'products:product-metrics' product.id %}">{% trans 'View' %}</a>]</td>
                        <td><a href='{{ product.url}}'>{{ product.url }}</a></td>
                        {% if request.user.is_staff %}
                            <td>{{ product.id }}</td>
                            <td>{{ product.internalId }}</td>
                        {% endif %}
                        <td>{{ product.price }}</td>
                        <td>{{ product.stock }}</td>
                        <td>{{ product.sales }}</td>
                        <td>{{ product.pageviews }}</td>
                        <td>{{ product.weight }}</td>
                        <td>{{ product.sales_rate|floatformat:3 }}</td>
                        <td>
                            <a href="{% url 'products:product-similar' product.id %}">
                                {{ product.similar_products_num }}
                            </a>
                        </td>
                        <td>
                            {% if request.user.is_staff %}
                                <a class="editable editable-click js-manual-similar-products" 
                                    href="#"
                                    data-pk="{{ product.id }}"
                                    data-url="{% url 'products:update' product.id %}"
                                    data-type="text"
                                    data-name="manual_similar_products_num">
                            {% else %}
                                <a href="">
                            {% endif %}
                                {{ product.manual_similar_products_num }}
                            </a>
                        </td>
                        <td>{{ product.updated|date:"d/m/y H:i" }}</td>
                        <td>
                            <a href="{% url 'products:product-similar-images' product.id %}">
                                {{ product.similar_image_products_num }}
                            </a>
                        </td>
                        <td>
                          {% if product.in_stock %}
                          &#9989;
                          {% else %}
                          &#10060;
                          {% endif %}
                        </td>
                        {% if request.user.is_staff %}
                            <td>{% if request.user.is_authenticated %}<a href="{% url 'products:update' product.id %}">{% trans 'Update' %}</a>{% else %}-{% endif %}</td>
                            <td>{% if request.user.is_authenticated %}<a href="{% url 'products:delete' product.id %}">{% trans 'Delete' %}</a>{% else %}-{% endif %} </td>
                            <td>
                                <a href="{% url 'products:visitor-status' product.id %}">List visitor status</a>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="jumbotron">
        {% if form.errors %}
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {% for field in form %}
                    {% if field.errors %}
                    <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <form method="POST" action=".">
            {% csrf_token %}
            <div class="form-group">
                {{ form.feedback.label_tag }}
                {{ form.feedback }}
            </div>
            <input type="submit" class="btn btn-primary" value="Submit" />
        </form>
    </div>

{% endblock %}

{% block javascript %}
    {{ block.super }}
    {# <script src="//cdnjs.cloudflare.com/ajax/libs/eldarion-ajax/0.12.0/eldarion-ajax.min.js"></script> #}
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
{% endblock %}

templates/products/product_form.html
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="hidden" name="next" value="{{ next }}" />
  <input type="submit" value="Create" />
</form>

templates/products/product_metrics.html
{% extends "common/base.html" %}
{% load i18n %}

{% block content %}
    <table class="table table-bordered">
            <caption>
                <strong>{{ product.title }}</strong>
                {% if product.category %}
                    from category {{ product.category }}
                {% endif %}    
                <br />

                <a href="{{ product.url }}" target="_blank">{{ product.url }}</a>
            </caption>
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>{% trans 'Price' %}</th>
                <th>{% trans 'Page Views' %}</th>
                <th>{% trans 'Likes' %}</th>
                <th>{% trans 'Sales' %}</th>
                <th>{% trans 'Weight' %}</th>
                <th>CompetitorNumber</th>
                {% if request.user.is_staff %}
                    <th>{% trans 'Update' %}</th>
                    <th>{% trans 'Delete' %}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for metric in metrics %}
                <tr>
                    <td>{{ metric.timestamp }}</td>
                    <td>{{ metric.price }}</td>
                    <td>{{ metric.pageviews }}</td>
                    <td>{{ metric.likes }}</td>
                    <td>{{ metric.sales }}</td>
                    <td>{{ metric.weight|floatformat:2 }}</td>
                    <td>{{ metric.competitornumber }}</td>
                    {% if request.user.is_staff %}
                        <td> <a href="{% url 'products:update-metrics' metric.id %}">{% trans 'Update' %}</a> </td>
                        <td> <a href="{% url 'products:delete-metrics' metric.id %}">{% trans 'Delete' %}</a> </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <a href="javascript:void(0);" id="similar-banner"><img src="{{ STATIC_URL }}" alt="similar products"></a>
      </div>
    </div>
{% endblock content %}

{% block extra_js %}

  <script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
      $('#similar-banner').on('click', function() {
        console.log("Similar product");
        ga('send', 'event', 'product', 'click', 'similar product');
      });
    });
  </script>
{% endblock %}

templates/products/product_similar.html
{% extends "common/base.html" %}
{% load i18n %}

{% block content %}
    <table class="table table-bordered">
      <caption><a href="{{ object.url }}">{{ object.title }}</a></caption>
        <thead>
            <tr>
                <th>Title</th>
                <th>Url</th>
            </tr>
        </thead>
        <tbody>
            {% for p in product.similar_products.all %}
                <tr>
                    <td>{{ p.title }}</td>
                    <td><a href='{{ p.url}}'>{{ p.url }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/products/visitorstatus_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete?</p>
    <input type="submit" value="Confirm" />
</form>