apps/products/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

import views


urlpatterns = [
    url(r'^metrics/create/$', views.MetricFormView.as_view(), name='metrics-create'),
    url(r'^metrics/update/(?P<pk>.*\d+)/$', views.UpdateMetrics.as_view(), name='update-metrics'),
    url(r'^metrics/delete/(?P<pk>.*\d+)/$', views.DeleteMetrics.as_view(), name='delete-metrics'),
    url(r'^(?P<pk>.*\d+)/metrics/$', views.ProductMetricsView.as_view(), name='product-metrics'),
    url(r'^metrics/$', views.MetricsView.as_view(), name='metrics'),

    url(r'^similar/(?P<pk>.*\d+)/$', views.ProductSimilarView.as_view(), name='product-similar'),
    url(r'^similar-images/(?P<pk>.*\d+)/$', views.ProductSimilarImagesView.as_view(), name='product-similar-images'),
    url(r'^selling/$', views.ProductSellingSpeedView.as_view(), name='selling_speed'),

    url(r'^create/$', views.CreateProduct.as_view(), name='create'),
    url(r'^download/$', views.download_file, name='download'),
    url(r'^download_status/$', views.download_status, name='download_status'),

    url(r'update/(?P<pk>.*\d+)/$',
        views.ProductUpdateView.as_view(),
        name='update'),

    url(r'delete/(?P<pk>.*\d+)/$',
        views.ProductDeleteView.as_view(),
        name='delete'),

    url(r'^VisitProduct/(?P<myAffiliateId>.+)/$', views.VisitProduct),

    url(r'^visitor-status/(?P<pk>.*\d+)/$', login_required(views.ListVisitorStatus.as_view()), name='visitor-status'),
    url(r'^VisitorStatus/Delete/(?P<pk>[0-9]+)/next=(?P<next>.+)/$',
        views.DeleteVisitorStatusView.as_view(),
        name='DeleteVisitorStatus'),

    url(r'^$', views.ProductListView.as_view(), name='list'),
]

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
#from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.views import login, logout
from django.views.generic import TemplateView

import views

urlpatterns = [
    url(r'^signup/$', views.RegisterUser, name='signup'),
    url(r'^confirm/(?P<activation_key>\w+)/', views.register_confirm),
    url(r'^signin/$', login, name='login', kwargs={"template_name": "users/login.html"}),
    url(r'^logout_confirm/$', TemplateView.as_view(template_name='users/logout.html'), name="logout_confirm"),
    url(r'^logout/$', logout, name='logout'),
]

goodobtain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from products.views import AdminCrawlSpiderView, AdminScrapyFormView
from . views import IndexView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view()),

    url(r'^admin/scrapy-crawl/(?P<spider>.*\w+)/$', AdminCrawlSpiderView.as_view(), name='crawl-spider'),
    url(r'^admin/scrapy/$', AdminScrapyFormView.as_view(), name='scrapy'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^crawler/', include('crawler.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^captcha/', include('captcha.urls')),
)

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += patterns('',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )
    except ImportError:
        pass

templates/common/base.html
{% load staticfiles i18n %}{% spaceless %}<!DOCTYPE html>
<html lang="en" ng-app>
<head>
  <meta charset="utf-8">
  <title>{% block title %}affiliate{% endblock title %}</title>

	<meta property="og:url" content="http://www.aybud.com/products/" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Database products" />
	<meta property="og:description" content="Database Bukalapak, Tokopedia, Lazada.... temukan produk-produk yang bisa menghasilkan uang dengan mudah" />
	<meta property="og:image" content="http://www.aybud.com/static/images/imgpsh_fullsize.png" />


  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Database Bukalapak, Tokopedia, Lazada.... temukan produk-produk yang bisa menghasilkan uang dengan mudah">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />

    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}" />

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% comment %}
    {% block angular %}
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular.min.js"></script>
    {% endblock %}
    {% endcomment %}

    <!-- Google Analytics Script -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-85349376-1', 'auto');
      ga('send', 'pageview');

    </script>
</head>

<body>

    <nav class="navbar navbar-default navbar-i_nverse  navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/"><span class="glyphicon glyphicon glyphicon-shopping-cart _glyphicon-home"></span> Products</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
    
            {% comment %}
            {# TODO use form in the navigationbar instead of form in jumbotron #}
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            {% endcomment %}
            <div class="collapse navbar-collapse" id="navigationbar">
                <ul class="nav navbar-nav">
                    {% if user.is_staff %}
                    <li><a class="glyphicon glyphicon-stats" href="{% url 'products:selling_speed' %}"> Selling</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav pull-right">
                    {% if request.user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#"
                                class="dropdown-toggle glyphicon glyphicon-user"
                                data-toggle="dropdown"
                                role="button"
                                aria-haspopup="true"
                                aria-expanded="false"> {{ user.username }} </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                                {% if request.user.is_superuser %}
                                    <li><a href="/admin/" target="_balnk">Admin</a></li>
                                {% endif %}
                                {# <li><a href="#">some piece of Action</a></li> #}
                                <li role="separator" class="divider"></li>
                                <li><a class="glyphicon glyphicon-log-out" href="{% url 'users:logout_confirm' %}"> Logout</a></li>
                            </ul>
                        </li> <!-- dropdown li -->
                    {% else %}
                        <li class="dropdown">
                            <a href="#"
                                class="dropdown-toggle glyphicon glyphicon-log-in"
                                data-toggle="dropdown"
                                role="button"
                                aria-haspopup="true"
                                aria-expanded="false"> Login</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a class="glyphicon glyphicon-log-in" href="{% url 'users:login' %}"> Login</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
             </div>
         </div>
    </nav> 
    
    {% comment %}
    {# TODO check if following commented lines are needed #}
    <ul class="nav navbar-nav">
      {% if not request.tenant.schema_name == "public" %}
        {% block Navigator%}
            <a class="navbar-brand" href="{% url 'products:list' %}">{% trans 'Products' %}</a>
            {% if request.user.is_staff and request.tenant %}
              <a class="navbar-brand" href="{% url 'users:ListUsers' %}">{% trans "Users" %}</a>
              <a class="navbar-brand" href="{% url 'ecmanager:providers-list' %}">Providers</a>
              <a class="navbar-brand" href="{% url 'ecmanager:orders-list' %}">Orders</a>
              <a class="navbar-brand" href="{% url 'ecmanager:ListAds' %}">Ads</a>
            {% endif %}
        {% endblock %}
      {% endif %}
    </ul>
    {% endcomment%}

  <div class="container">

    {% block messages %}
    {% for message in messages %}
    <div class="alert alert-dismissable fade in alert-{{ message.tags }}">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p>{{message}}</p>
    </div>
    {% endfor %}
    {% endblock messages %}

<div style="text-align: center;">
    <div class="fb-share-button" data-href="http://aybud.com/products/" data-layout="box_count" data-size="large" data-mobile-iframe="true">
        <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%aybud.com%2Fproducts%2F&amp;src=sdkpreparse">Поделиться</a>
    </div>
    <h1>{% trans 'Apa Yang Bagus Untuk Dijual' %}</h1><br>
</div>
   {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

  </div> <!-- /container -->

  {% block modal %}{% endblock modal %}

  <!-- Placed at the end of the document so the pages load faster -->
  {% block javascript %}
  <!-- Latest JQuery -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% endblock javascript %}

  {% block extra_js %}
    <!-- Your stuff: Third-party javascript libraries go here -->
  {% endblock %}

  <!-- place project specific Javascript in this file -->
  <script src="{% static 'js/project.js' %}"></script>

    <!-- FB share-->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

</body>
</html>{% endspaceless %}

templates/common/confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete this item?</p>
  <input type="submit" value="Confirm" />
</form>

templates/common/create.html
{% extends "common/base.html" %}
{% load i18n static %}

{% block title %}Create{% endblock title %}

{% block content %}
    <div class="row">
        <form method="POST" action=".">
            {% csrf_token %}
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <input type="hidden" name="next" value="{{ next }}" />
                            <input type="submit" class="btn btn-primary" value="Create" />
                        </td>
                    </tr>
                </tfoot>
            </table>
        </form>
    </div>

{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'ecmanager/select_and_populate.js' %}"></script>
{% endblock %}

templates/common/list.html
{% extends "common/base.html" %}
{% load i18n %}

{% block title %}{% endblock title %}

{% block content %}
<form action="." method="POST">
  {% csrf_token %}
	{% block createNewItem %}{% endblock %}

  <table class="table">
		<tr width='100%'>
			{% block fieldTitles %}{% endblock %}
		</tr>
		<tr width='100%'>
			{% block fieldContent %}{% endblock %}
		</tr>
  </table>
</form>
{% endblock content %}

templates/common/update.html
{% load i18n %}

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="{% trans 'Update' %}" />
</form>