apps/products/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

import views


urlpatterns = [
    url(r'^metrics/create/$', views.MetricFormView.as_view(), name='metrics-create'),
    url(r'^metrics/update/(?P<pk>.*\d+)/$', views.UpdateMetrics.as_view(), name='update-metrics'),
    url(r'^metrics/delete/(?P<pk>.*\d+)/$', views.DeleteMetrics.as_view(), name='delete-metrics'),
    url(r'^(?P<pk>.*\d+)/metrics/$', views.ProductMetricsView.as_view(), name='product-metrics'),
    url(r'^metrics/$', views.MetricsView.as_view(), name='metrics'),

    url(r'^similar/(?P<pk>.*\d+)/$', views.ProductSimilarView.as_view(), name='product-similar'),
    url(r'^similar-images/(?P<pk>.*\d+)/$', views.ProductSimilarImagesView.as_view(), name='product-similar-images'),
    url(r'^selling/$', views.ProductSellingSpeedView.as_view(), name='selling_speed'),

    url(r'^create/$', views.CreateProduct.as_view(), name='create'),
    url(r'^download/$', views.download_file, name='download'),
    url(r'^download_status/$', views.download_status, name='download_status'),

    url(r'update/(?P<pk>.*\d+)/$',
        views.ProductUpdateView.as_view(),
        name='update'),

    url(r'delete/(?P<pk>.*\d+)/$',
        views.ProductDeleteView.as_view(),
        name='delete'),

    url(r'^VisitProduct/(?P<myAffiliateId>.+)/$', views.VisitProduct),

    url(r'^visitor-status/(?P<pk>.*\d+)/$', login_required(views.ListVisitorStatus.as_view()), name='visitor-status'),
    url(r'^VisitorStatus/Delete/(?P<pk>[0-9]+)/next=(?P<next>.+)/$',
        views.DeleteVisitorStatusView.as_view(),
        name='DeleteVisitorStatus'),

    url(r'^$', views.ProductListView.as_view(), name='list'),
]

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
#from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.views import login, logout
from django.views.generic import TemplateView

import views

urlpatterns = [
    url(r'^signup/$', views.RegisterUser, name='signup'),
    url(r'^confirm/(?P<activation_key>\w+)/', views.register_confirm),
    url(r'^signin/$', login, name='login', kwargs={"template_name": "users/login.html"}),
    url(r'^logout_confirm/$', TemplateView.as_view(template_name='users/logout.html'), name="logout_confirm"),
    url(r'^logout/$', logout, name='logout'),
]

goodobtain/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from products.views import AdminCrawlSpiderView, AdminScrapyFormView
from . views import IndexView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view()),

    url(r'^admin/scrapy-crawl/(?P<spider>.*\w+)/$', AdminCrawlSpiderView.as_view(), name='crawl-spider'),
    url(r'^admin/scrapy/$', AdminScrapyFormView.as_view(), name='scrapy'),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^crawler/', include('crawler.urls')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^captcha/', include('captcha.urls')),
)

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += patterns('',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )
    except ImportError:
        pass

apps/users/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime


class User(AbstractUser):
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'award']

    award = models.IntegerField(default=0)

    def __unicode__(self):
        return self.username

    def get_rewarded(self):
        self.award += 10
        self.save()

    def GetRewarded(self):
        pass


def get_valid_thru_date():
    """ Returns date: current date + 1 day """
    return datetime.date.today() + datetime.timedelta(days=1)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=get_valid_thru_date)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'User profiles'

apps/users/forms.py
# -*- coding: utf-8 -*-
import re

from django import forms
from django.forms.utils import ErrorList
from django.utils.translation import ugettext_lazy as _

from captcha.fields import CaptchaField

from .models import User

class UserForm(forms.ModelForm):
  password = forms.CharField(widget=forms.PasswordInput,
    label="Password")
  password1 = forms.CharField(widget=forms.PasswordInput,
    label="Confirm password")

  def clean_username(self):
    username_form = self.cleaned_data['username']
    if User.objects.filter(username=username_form).exists():
      raise forms.ValidationError(_("Username is already taken"))
    return username_form

  def clean(self):
    pwd = self.cleaned_data.get('password', "")
    pwd1 = self.cleaned_data.get('password1', "")
    if pwd != pwd1:
      if self._errors.get('password1', None) is None:
        self._errors['password1'] = ErrorList()
      self._errors['password1'].append(_("Passwords are not equal"))
    return self.cleaned_data

  def save(self):
    kwargs = self.cleaned_data.copy()
    del kwargs['password1']
    return User.objects.create_user(**kwargs)

  class Meta:
    model = User
    fields = "username", "password", "password1", "email"

from django import forms
#from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'E-mail address'}))
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    captcha = CaptchaField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2', 'captcha')

    #clean email field
    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            # Seems this cause 'relation "auth_user" does not exist' error [](http://james.lin.net.nz/2013/06/08/django-custom-user-model-in-admin-relation-auth_user-does-not-exist/)
            #User._default_manager.get(email=email)
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('duplicate email')

    def clean_password1(self):
        has_lower = False
        has_upper = False
        has_digit = False
        has_special = False
        password = self.cleaned_data.get("password1")
        if len(password) < 10:
            raise forms.ValidationError("Password must be at least 10 characters long.")

        for char in password:
            if not has_upper and char.isupper():
                    has_upper = True

            if not has_lower and char.islower():
                    has_lower = True

            if not has_digit and char.isdigit():
                    has_digit = True

            if not has_special and not re.match("^[a-zA-Z0-9]*$", char):
                has_special = True

        if not has_upper or not has_lower or not has_digit or not has_special:
            raise forms.ValidationError("Password must have at least 1 lowercase, 1 uppercase, 1 digit, and 1 special character in it.")

        return password


    #modify save() method so that we can set user.is_active to False when we first create our user
    def save(self, commit=True):    
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.is_active = False # not active until he opens activation link
            user.save()

        return user

apps/users/views.py
# -*- coding: utf-8 -*-
from django.views.generic import CreateView
#from django.core.urlresolvers import reverse
#from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.conf import settings
from django.http import HttpResponse

#from .forms import UserForm
from .models import User


MIN_REQUEST_AMOUNT = getattr(settings, 'AFFILIATE_MIN_BALANCE_FOR_REQUEST', 0)

from django.shortcuts import render_to_response, get_object_or_404
from django.core.context_processors import csrf
from forms import *
from django.core.mail import send_mail
import hashlib
import datetime
import random
from django.utils import timezone


def RegisterUser(request):
  args = {}
  args.update(csrf(request))
  if request.method == 'POST':
    form = RegistrationForm(request.POST)
    args['form'] = form
    if form.is_valid():
      form.save()  # save user to database if form is valid

      username = form.cleaned_data['username']
      email = form.cleaned_data['email']
      salt = hashlib.sha1(str(random.random())).hexdigest()[:5]      
      activation_key = hashlib.sha1(salt+email).hexdigest()      
      key_expires = datetime.datetime.today() + datetime.timedelta(2)

      #Get user by username
      user=User.objects.get(username=username)

      # Create and save user profile                                                                  
      new_profile = UserProfile(user=user, activation_key=activation_key, key_expires=key_expires)
      new_profile.save()

      # Send email with activation key
      email_subject = 'Account confirmation'
      email_body = "Hey %s, thanks for signing up." % username
      email_body += "To activate your account, click this link within 48hours %s/users/confirm/%s" % (request.get_host(), activation_key)

      send_mail(email_subject, email_body, 'Frz6Jbf9@gmail.com', [email], fail_silently=False)

      return util.WaitAndRedirect(request, '/users/signup', 'pre-regitration succeeded.')    
  else:
    args['form'] = RegistrationForm()

  return render_to_response('users/register.html', args)

def register_confirm(request, activation_key):
  #check if user is already logged in and if he is redirect him to some other url, e.g. home
  if request.user.is_authenticated():
    HttpResponseRedirect('/home')

  # check if there is UserProfile which matches the activation key (if not then display 404)
  user_profile = get_object_or_404(UserProfile, activation_key=activation_key)

  #check if the activation key has expired, if it hase then render confirm_expired.html
  if user_profile.key_expires < timezone.now():
    #return render_to_response('user_profile/confirm_expired.html')
    return util.WaitAndRedirect(request, '/users/signup', 'confirmation expired. Please register again.')
  #if the key hasn't expired save user and set him as active and render some template to confirm activation
  user = user_profile.user
  user.is_active = True
  user.save()
  #return render_to_response('user_profile/confirm.html')
  return util.WaitAndRedirect(request, '/users/signin', 'mail confirmed. The registration is done.')

templates/users/list.html
{% extends "common/list.html" %}
{% load i18n %}

{% block title %}Orders{% endblock title %}

{% block createNewItem %}
	{% if request.user.is_staff %}
		<a href='/users/signup/'>create user</a>
	{% endif %}
{% endblock %}

{% block fieldTitles %}
  <td>name</td>
  <td>email</td>
  <td>award</td>
  <td>{% trans 'Update' %}</td>
  <td>{% trans 'Delete' %}</td>
{% endblock %}

{% block fieldContent %}
    {% for user in users %}
    <tr>
      <td>{{ user.username}}{% if user.is_staff %}(staff){% endif %}</td>
      <td>{{ user.email}}</td>
      <td>{{ user.award}}</td>
      <td> <a href='/users/UpdateUser/{{user.id}}/'>{% trans 'Update' %}</a> </td>
      <td> <a href='/users/DeleteUser/{{user.id}}/'>{% trans 'Delete' %}</a> </td>
    </tr>
    {% endfor %}
{% endblock %}

templates/users/login.html
{% extends "common/base.html" %}
{% load i18n %}
{% load url from future %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
	{% if user.is_staff %}
		is staff
	{% else %}
		is not staff
	{%endif%}

	<div class="container">
		<div class="row">
			<div class="col-md-5">
				<h2>{% trans "Sign In" %}</h2>
				<form class="login" method="POST" action=".">
					{% csrf_token %}
					{{ form|crispy }}
					<input type="hidden" name="next" value="{% if 'next' in request.GET %}{{request.GET.next}}{% else %}{% url 'products:list' %}{%endif%}" />
          <p></p>
					<button class="btn btn-success" type="submit">{% trans "Sign In" %}</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/users/logout.html
{% extends "common/base.html" %}

{% load i18n %}

{% block title %}{% trans "Logout" %}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-5">

        <h2>{% trans "Logout" %}</h2>

        <p>{% trans 'Are you sure you want to logout?' %}</p>

        <form method="post" action="{% url 'users:logout' %}">
          {% csrf_token %}
          <input type="hidden" name="next" value="{% url 'products:list' %}"/>
          <button class="btn btn-danger" type="submit">{% trans 'Logout' %}</button>
        </form>
    </div>
  </div>
</div>

{% endblock %}

templates/users/register.html
{% extends "common/base.html" %}

{% block content %}            
<form class="form-signup" action="/users/signup/" method="post">
    {% csrf_token %}
    <h2>Create your account</h2>
    <div class="fieldWrapper">
        {{ form.first_name.errors }} 
        <label>First name</label><br>
        {{ form.first_name }}
    </div>    
    <br>
    <div class="fieldWrapper">
        {{ form.last_name.errors }}  
        <label>Last name</label><br>
        {{ form.last_name }}
    </div>    
    <br>
    <div class="fieldWrapper">    
        {{ form.email.errors }}            
        <label>E-mail</label><br>
        {{ form.email }}
    </div>    
    <br>
    <div class="fieldWrapper">
        {{ form.username.errors }}                
        <label>Username</label><br>
        {{ form.username }}
    </div>
    <br>
    <div class="fieldWrapper">        
        {{ form.password1.errors }}             
        <label>Password</label><br>                    
        {{ form.password1 }}
    </div>
    <br>
    <div class="fieldWrapper">   
        {{ form.password2.errors }}          
        <label>Password again</label><br>
        {{ form.password2 }}
    </div>
    <br>
    <div class="fieldWrapper">   
        {{ form.captcha.errors }}          
        <label>Captcha</label><br>
        {{ form.captcha }}
    </div>
    <br></br>
    <input type="submit" name="submit" class="btn btn-primary" value="Create account">
</form>

{% endblock %}

templates/users/signup.html
{% extends "common/base.html" %}

{% load url from future %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Signup" %}{% endblock title %}

{% block content %}
<h1>{% trans "Sign Up" %}</h1>

<form class="signup" id="signup_form" method="post" action=".">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="hidden" name="next" value="{% url 'products:list' %}" />
  <button class="btn btn-success" type="submit">{% trans "Sign Up" %} &raquo;</button>
</form>

{% endblock content %}